#ifndef _FLASH_LAYOUT_H_
#define _FLASH_LAYOUT_H_

#include <hardware/flash.h>
#include <pico/platform.h>

#ifndef PERSISTED_CONFIG_SIZE
#define PERSISTED_CONFIG_SIZE 4096
#endif

#ifndef PICO_FLASH_BANK_TOTAL_SIZE
#define PICO_FLASH_BANK_TOTAL_SIZE (FLASH_SECTOR_SIZE * 2u)
#endif

#if PICO_RP2350
#define REMAPPER_CONFIG_OFFSET_IN_FLASH (PICO_FLASH_SIZE_BYTES - PERSISTED_CONFIG_SIZE - FLASH_SECTOR_SIZE)
#define REMAPPER_FLASH_BANK_STORAGE_OFFSET (REMAPPER_CONFIG_OFFSET_IN_FLASH - PICO_FLASH_BANK_TOTAL_SIZE)
#else
#define REMAPPER_CONFIG_OFFSET_IN_FLASH (PICO_FLASH_SIZE_BYTES - PERSISTED_CONFIG_SIZE)
#define REMAPPER_FLASH_BANK_STORAGE_OFFSET (REMAPPER_CONFIG_OFFSET_IN_FLASH - PICO_FLASH_BANK_TOTAL_SIZE)
#endif

#endif
