name: release
on:
  push:
    tags: 'r*'
jobs:
  build-nrf52:
    uses: ./.github/workflows/build-nrf52.yml
  create-release:
    needs: [ build-nrf52 ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: download
      - uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          draft: true
          files: download/*
